services:
  mariadb:
    image: 'mariadb:11.4'
    container_name: beautybox-mariadb
    environment:
      - 'MARIADB_DATABASE=beautyboxdb'
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=no'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - beautybox-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
    driver: local

networks:
  beautybox-network:
    driver: bridge
